### ISSUE TITLE
SublimeLinter: reason: [Errno 13] Permission denied  (lslint)

### ISSUE THREAD

**Issue by Lunardis** [buildersbrewery/sublime-lsl#3] opened 2017-12-26 23:11 UTC
Get a error-message in console that the directory/file for **lslint** wasn't found or permission is when startup Sublime.

### Actual behavior

**No lint and following error-message in console:**

```text
SublimeLinter: ERROR: could not launch ['/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/bin/lslint/osx/lslint', '--version'] 
SublimeLinter: reason: [Errno 13] Permission denied 
SublimeLinter: PATH: /usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin 
SublimeLinter: WARNING: no lslint version could be extracted from:
 
CodeFormatter: Plugin Initialized
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/main.py", line 94, in plugin_loaded
    chmod_lslint()
  File "/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/main.py", line 85, in chmod_lslint
    stat.S_IXOTH)
FileNotFoundError: [Errno 2] No such file or directory: '=BB= LSL/bin/lslint/linux/lslint'
```

I've looked into the directory and the files are available, and they're:

* `/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/bin/lslint/linux/lslint`
* `/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/bin/lslint/osx/lslint`

**Terminal:**

```text
drwxr-xr-x   3 slunardi  staff     102 26 Dez 23:13 .
drwxr-xr-x  10 slunardi  staff     340 26 Dez 23:35 ..
-rw-r--r--   1 slunardi  staff  406040 26 Dez 23:13 lslint
```

Tried also to do **chmod +x lslint** but even with executable attribute, it doesn't work. I can't even execute it in the Terminal.

I can touch, edit, modify the file, so it can't be a permission issue.

Settings are set as like in the guidelines. (do i need to add the lsl-linter into the SublimeLinter settings, too? (just have add the code of the guidelines into my Preferences.sublime-settings for user.

**Sublime-User-Preferences:**

```json
{
	"color_scheme": "Packages/User/SublimeLinter/base16-ocean.light (SL).tmTheme",
	"font_size": 13,
	"ignored_packages":
	[
		"Vintage"
	],
	"tab_size": 4,
	"theme": "Default.sublime-theme",
	"translate_tabs_to_spaces": true,

    "mdpopups.sublime_user_lang_map": { 
        "lsl": [
            [ "lsl" ],
            [ "=BB= LSL/.sublime/syntaxes/LSL" ]
        ]
    },
    "mdpopups.use_sublime_highlighter": true
}
```

### Environment

```text
=BB= LSL:
    version: 1.4.1
    installed via Package Control: True

Sublime Text:
    channel: stable
    build: 3143
    portable: False
    platform: MacOS Sierra ( 10.12.6 )
    architecture: x64
```

**Comment by buildersbrewery** [comment] 2017-12-26 23:38
Thanks for the report. This seems to be a duplicate of #1, also there's more discussion about this at Makopo/lslint#66.

---

I had added the file via git with:

```text
git add --chmod=+x bin/lslint/osx/lslint
```

If you look at `./main.py`, it modifies the file when the plugin is loaded via:

```python
os.chmod(pathToModify,
         stat.S_IRUSR |
         stat.S_IWUSR |
         stat.S_IXUSR |
         stat.S_IRGRP |
         stat.S_IXGRP |
         stat.S_IROTH |
         stat.S_IXOTH)
```

Currently I don't have a mac to test this. I'll report back as soon as I have a solution.

**Comment by MisterFoxi** [comment] 2017-12-30 07:37
Did you allows lslint to be executed with the security panel if the code is not signed in case you are on Sierra or High Sierra. ?

**Comment by Lunardis** [comment] 2017-12-30 14:18
I've turned the Security restrictions off.
![image](https://user-images.githubusercontent.com/19334757/34454864-3cc8c256-ed74-11e7-9af2-df89ef543b94.png)

Also my SIP is currently disabled, so there should come no restriction from this side. I know that this isn't smart, but I'm annoyed that I've to disable, update an app, reenable the whole SIP again and again when some of my injecting-apps are updating. (like Totalfinder)

**Comment by buildersbrewery** [comment] 2017-12-30 23:55
Some feedback from another mac user:

* lslint binary has `chmod 755`
* no errors, neither from the OS nor from Sublime nor from SublimeLinter
* building and linting works fine
* tested on `macOS Sierra 10.12.6`
* `lslint --version` correctly reports `v1.0.8`

**Comment by MisterFoxi** [comment] 2017-12-31 08:00
Same for me but I got lslint under `/usr/local/bin`

**Comment by Lunardis** [comment] 2017-12-31 12:07
/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/bin/lslint
```
    Type: lslint --version
Response: -bash: lslint: command not found
```
```
    Type: ./lslint --version
Response: lslint v1.0.8
```
If I copy lslint to /usr/local/bin it is accessable without ./ prefix. But this doesn't solves the error message:


```
reloading plugin =BB= LSL.main
SublimeLinter: lslint linter loaded 
reloading plugin SublimeLinter.commands
reloading plugin SublimeLinter.sublimelinter
plugins loaded
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/main.py", line 94, in plugin_loaded
    chmod_lslint()
  File "/Users/slunardi/Library/Application Support/Sublime Text 3/Packages/=BB= LSL/main.py", line 85, in chmod_lslint
    stat.S_IXOTH)
FileNotFoundError: [Errno 2] No such file or directory: '=BB= LSL/bin/lslint/linux/lslint'
environment variables loaded using: /bin/bash -l
```

I thought that the equal-character ( = ) could be a problem and should be escaped. Tryed it, but that was a stupid idea, because it works for you and didn't changed something for me.

I overwrite all permssions again, same result.
Cloned the master and put it into "Sublime Text 3/Pacakages/", same result.
Turned off all Pacakges except "SublimeLinter" and "=BB= LSL", same result.

I just get the error message, which is really odd if it works for you.

**Comment by buildersbrewery** [comment] 2017-12-31 12:25
This works for other users on mac with Sierra.

I personally only use Win10 Pro x64.

---

Could it be that you're forcing SublimeLinter to run lslint via bash and that causes the error?

**Comment by Lunardis** [comment] 2017-12-31 23:14
How to run SublimeLinter via Bash? I just installed it here for this package. (a real configured version I only have at work)

**SublimeLinter Config:**

```json
{
    "user": {
        "debug": false,
        "delay": 0.25,
        "error_color": "D02000",
        "gutter_theme": "Packages/SublimeLinter/gutter-themes/Default/Default.gutter-theme",
        "gutter_theme_excludes": [],
        "lint_mode": "background",
        "linters": {
            "lslint": {
                "@disable": true,
                "args": [],
                "excludes": []
            }
        },
        "mark_style": "outline",
        "no_column_highlights_line": false,
        "passive_warnings": false,
        "paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "python_paths": {
            "linux": [],
            "osx": [],
            "windows": []
        },
        "rc_search_limit": 3,
        "shell_timeout": 10,
        "show_errors_on_save": false,
        "show_marks_in_minimap": true,
        "syntax_map": {
            "html (django)": "html",
            "html (rails)": "html",
            "html 5": "html",
            "javascript (babel)": "javascript",
            "magicpython": "python",
            "php": "html",
            "python django": "python",
            "pythonimproved": "python"
        },
        "tooltip_fontsize": "1rem",
        "tooltip_theme": "Packages/SublimeLinter/tooltip-themes/Default/Default.tooltip-theme",
        "tooltip_theme_excludes": [],
        "tooltips": false,
        "use_current_shell_path": false,
        "warning_color": "DDB700",
        "wrap_find": true
    }
}
```

**Comment by myggenresident** [comment] 2017-12-31 23:19
You paste an error `FileNotFoundError: [Errno 2] No such file or directory: '=BB= LSL/bin/lslint/linux/lslint` which is a sign that something is wrong in your file structure. The file exists even on an osx system (even though not used). Did you remove it manually, or did the install have errors?

In your initial bug report you see that it tries to run the linux binary, which is obviously not going to work on osx. Why would it do that?

Don't play around in /usr/local/bin if you're not sure what you're doing. A normal install will go into your home directory.

What's happening that your system is so different?

**Comment by Lunardis** [comment] 2018-01-01 00:02
> You paste an error FileNotFoundError: [Errno 2] No such file or directory: '=BB= LSL/bin/lslint/linux/lslint which is a sign that something is wrong in your file structure. The file exists even on an osx system (even though not used). Did you remove it manually, or did the install have errors?
I know and I tested it already several times, **the files really exist**!

```bash
cd /Users/slunardi/Library/Application\ Support/Sublime\ Text\ 3/Packages/\=BB\=\ LSL/
ls -laR > directory.txt
```

Output: [On PasteBin](https://pastebin.com/Z8i3Ffgb)

Everytime I tried now to change something to find out the reason, I removed the whole package and reinstalled it.

> In your initial bug report you see that it tries to run the linux binary, which is obviously not going to work on osx. Why would it do that?

Because it is the first entry of the **binaryPaths-array** of the [**main.py**](https://github.com/buildersbrewery/sublime-lsl/blob/master/main.py#L24-L73). I've already tried out what happend if I just remove the first entry and it just throw the same error then for the next entry of this list.

I also tried to replace everything there with absolute-paths, but same result like the umodified version of the file.

> Don't play around in /usr/local/bin if you're not sure what you're doing. A normal install will go into your home directory.

In this case I was aware about what I did.

> What's happening that your system is so different?

That's something I questioning myself currently now, too. Especially because it works for you all. I don't have so many deep injecting applications, especially none who could access... oh... what's about homebrew?

Could it be a reason? I don't remember that I've changed anything expect adding imagemagick for php5.6 but maybe something happened with python? (have no clue about Python)

**Currently I've installed:**

```
"Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
```

Installed Homebrew Packages:

```
      TYPE: brew list
RESPONSONE: freetype    imagemagick libtiff     openssl     readline
            gettext     jpeg        libtool     php56       unixodbc
            icu4c       libpng      libxml2     php56-imagick   xz
```

**Brew-Version:** Homebrew 1.4.1

**Comment by buildersbrewery** [comment] 2018-01-01 01:33
Sublime 3 ships with its own Python 3.3. On Windows it's in a zip in the same folder as the subl binary.

**Comment by buildersbrewery** [comment] 2018-01-01 01:46
Could you read <http://www.sublimelinter.com/en/latest/troubleshooting.html> and see if it helps you fixing your issue?

**Comment by buildersbrewery** [comment] 2018-01-03 10:13
Also, could you try if using the SublimeLinter `v4.0.0` (or later) fixes your issue? There's a lot of work being done on that currently.

https://github.com/SublimeLinter/SublimeLinter

via:

```json
//  in 'Packages/User/Package Control.sublime-settings'

    "install_prereleases":
    [
        "SublimeLinter"
    ]
```

The stable 4.0 release should be out soonish.

**Comment by buildersbrewery** [comment] 2019-01-24 02:45
@Lunardis could you check if v4.2.1 or later fixed the issue for you?

**Comment by buildersbrewery** [comment] 2019-02-05 08:57
@Lunardis please re-open if problems persist

**Closed as completed by buildersbrewery** 2019-02-05 08:57 UTC
Labels: arch:x64, awaiting:reply, needs:reproduction, platform:macos, status:maybe-fixed
